# Dockerfile

FROM golang:1.5.0
MAINTAINER @pottava

RUN go get -u github.com/robfig/cron
RUN go get -u github.com/fsouza/go-dockerclient
RUN go get -u golang.org/x/net/context
RUN go get -u github.com/docker/docker/pkg/parsers
